use_frameworks!

target 'WYUtils_Example' do
  pod 'WYUtils', :path => '../'
  pod 'Masonry'
  pod 'BlocksKit'
  pod 'LookinServer', :configurations => ['Debug']

  target 'WYUtils_Tests' do
    inherit! :search_paths

    
  end
end
