use_frameworks!

target 'WYUtils_Example' do
  pod 'WYUtils', :path => '../'
  pod 'Masonry'
  pod 'BlocksKit'
  pod 'LookinServer', :configurations => ['Debug']

  target 'WYUtils_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                 end
            end
     end
  end
end
